title: My Portfolio
description: Portfolio site for game dev projects
baseurl: "/portfolio"
url: "https://zephyr-62.github.io"
markdown: kramdown
collections:
  projects:
    output: true
include:
  - pages

